
import { GoogleGenAI, Type } from "@google/genai";

// Ensure the API key is available in the environment variables
if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable not set.");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Generates a list of image prompts from a given blog article.
 * @param articleText The text of the blog article.
 * @param existingPrompts Optional list of prompts that have already been generated to avoid duplicates.
 * @returns A promise that resolves to an array of strings (image prompts).
 */
export async function generatePromptsFromArticle(articleText: string, existingPrompts: string[] = []): Promise<string[]> {
  try {
    let promptText = `Here is a blog article:\n\n---\n${articleText}\n---\n\nPlease generate an array of 5 distinct and visually descriptive image prompts that capture the key themes and moments in this article.`;

    if (existingPrompts.length > 0) {
      promptText += `\n\nThe following prompts have already been generated. Please generate 5 NEW, DIFFERENT prompts that explore other aspects of the article or use different visual styles:\n${existingPrompts.map(p => `- ${p}`).join('\n')}`;
    }

    const response = await ai.models.generateContent({
      model: "gemini-2.5-pro",
      contents: promptText,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            prompts: {
              type: Type.ARRAY,
              description: "An array of 5 visually descriptive image prompts.",
              items: {
                type: Type.STRING,
                description: "A single, concise, and visually descriptive prompt."
              }
            }
          },
          required: ["prompts"],
        },
        systemInstruction: "You are an expert art director. Your task is to read a blog article and generate a series of concise, visually descriptive prompts for an AI image generator. The prompts should capture the key themes, concepts, or scenes from the article. The style should be photorealistic and cinematic unless the article suggests otherwise.",
      }
    });

    const jsonText = response.text.trim();
    const parsed = JSON.parse(jsonText);
    
    if (parsed && Array.isArray(parsed.prompts)) {
      return parsed.prompts;
    } else {
      console.error("Unexpected JSON structure:", parsed);
      throw new Error("Failed to parse prompts from the AI response.");
    }

  } catch (error) {
    console.error("Error generating prompts:", error);
    throw new Error("Could not generate image prompts from the article.");
  }
}

/**
 * Generates an image from a given prompt using the Imagen model.
 * @param prompt The text prompt to generate an image from.
 * @returns A promise that resolves to a base64-encoded image data URL.
 */
export async function generateImageFromPrompt(prompt: string): Promise<string> {
  try {
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: `${prompt}, photorealistic, cinematic lighting, high detail`,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/png',
        aspectRatio: '16:9',
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
      return `data:image/png;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error(`Error generating image for prompt "${prompt}":`, error);
    throw new Error(`Failed to generate an image for the prompt: "${prompt}"`);
  }
}
